site_name: 写项目文档的道术
nav:
  - README:
    - TM 文档学习: readme/tm.md

theme:
  name: 'material'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - plantuml

extra_css:
  - https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.css
  # - assets/one-dark.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js
  - assets/material_nav_extend.js

extra:
  search:
    language: 'cn'
